### ISSUE TITLE
언리얼 버전 질문

### ISSUE THREAD

**Issue by isln** [kookmin-sw/2019-cap1-2019_16#9]
현재 깃에 올라와있는 프로젝트가 언리얼엔진 버전 몇으로 제작된건가요?

그리고 지금 각자 개발하면서 사용중인 엔진 버전이 어떻게 되는지??

**Comment by github3051** [comment]
4.21.2 버전으로 진행하고 있습니다.

**Comment by 610ksh** [comment]
4.21.2 입니다~

**Comment by isln** [comment]
감사합니다~
